### PR TITLE
fix: resolve renderer via import.meta.resolve for pnpm compatibility

### LINKED ISSUE #64: Expected your framework's preset to export a `renderToCanvas` field.
I followed the instructions to set up Storybook and Astro, but I get this error on the Storybook web UI.

> Expected your framework's preset to export a `renderToCanvas` field.
>
> The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:
>
> 1. **Missing Context/Providers**: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the [Decorators documentation](https://storybook.js.org/docs/writing-stories/decorators).
> 2. **Misconfigured Webpack or Vite**: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring [Webpack](https://storybook.js.org/docs/builders/webpack) or [Vite](https://storybook.js.org/docs/builders/vite) with Storybook.
> 3. **Missing Environment Variables**: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the [Environment Variables documentation](https://storybook.js.org/docs/configure/environment-variables).
>
> ~~~
> Perhaps it needs to be upgraded for Storybook 7.0?
> More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-framework-field
> ~~~

Here are the errors from the browser console:

```
Error reading preview.js: [runtime.js:12162:54](http://localhost:6006/node_modules/.pnpm/storybook@10.3.5_@testing-library+dom@10.4.1_react-dom@19.2.5_react@19.2.5__react@19.2.5/node_modules/storybook/dist/preview/runtime.js)
    error runtime.js:12162
    renderPreviewEntryError runtime.js:34383
    renderPreviewEntryError runtime.js:34876
    getProjectAnnotationsOrRenderError runtime.js:34172
    initialize runtime.js:34151
    PreviewWithSelection runtime.js:34683
    PreviewWeb runtime.js:35100
    <anonymous> vite-app.js:11
```

```
SB_PREVIEW_API_0004 (MissingRenderToCanvasError): Expected your framework's preset to export a `renderToCanvas` field.

Perhaps it needs to be upgraded for Storybook 7.0?

More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-framework-field
    _StorybookError runtime.js:13575
    MissingRenderToCanvasError runtime.js:13689
    getProjectAnnotationsOrRenderError runtime.js:34169
    initialize runtime.js:34151
    PreviewWithSelection runtime.js:34683
    PreviewWeb runtime.js:35100
    <anonymous> vite-app.js:11
[runtime.js:12162:54](http://localhost:6006/node_modules/.pnpm/storybook@10.3.5_@testing-library+dom@10.4.1_react-dom@19.2.5_react@19.2.5__react@19.2.5/node_modules/storybook/dist/preview/runtime.js)
    error runtime.js:12162
    renderPreviewEntryError runtime.js:34383
    renderPreviewEntryError runtime.js:34876
    getProjectAnnotationsOrRenderError runtime.js:34172
    initialize runtime.js:34151
    PreviewWithSelection runtime.js:34683
    PreviewWeb runtime.js:35100
    <anonymous> vite-app.js:11
```

```
Uncaught (in promise) SB_PREVIEW_API_0004 (MissingRenderToCanvasError): Expected your framework's preset to export a `renderToCanvas` field.

Perhaps it needs to be upgraded for Storybook 7.0?

More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-framework-field
    _StorybookError runtime.js:13575
    MissingRenderToCanvasError runtime.js:13689
    getProjectAnnotationsOrRenderError runtime.js:34169
    initialize runtime.js:34151
    PreviewWithSelection runtime.js:34683
    PreviewWeb runtime.js:35100
    <anonymous> vite-app.js:11
[runtime.js:13575:5](http://localhost:6006/node_modules/.pnpm/storybook@10.3.5_@testing-library+dom@10.4.1_react-dom@19.2.5_react@19.2.5__react@19.2.5/node_modules/storybook/dist/preview/runtime.js)
    initialize runtime.js:34156
    AsyncFunctionThrow self-hosted:784
    (Async: async)
    PreviewWithSelection runtime.js:34683
    PreviewWeb runtime.js:35100
    <anonymous> vite-app.js:11
```

The configuration files are copy-pasted from the instructions, but here they are anyway just in case.

- `.storybook/main.js`
  ```javascript
  export default {
    stories: ['../src/**/*.stories.@(js|jsx|ts|tsx)'],
    framework: {
      name: '@storybook-astro/framework',
      options: {},
    },
  };
  ```
- `storybook/preview.ts`
  ```javascript
  const preview = {
    parameters: {
      controls: {
        matchers: {
          color: /(background|color)$/i,
          date: /Date$/i,
        },
      },
    },
  };
  export default preview;
  ```

The one story (`Button`) does get displayed in the side bar, it's only rendering that does not work.

### PR DESCRIPTION
**Pull request by lukemcd**
## Summary

- Fixes `MissingRenderToCanvasError` when using pnpm
- Changes `core.renderer` in the framework preset from a bare package specifier to an absolute path via `import.meta.resolve()`

## Root Cause

With pnpm's strict node_modules isolation, transitive dependencies are not hoisted to the project root. Storybook resolves `core.renderer` by searching upward from the `.storybook` directory — so the bare specifier `'@storybook-astro/renderer'` fails to resolve when the package only exists inside the framework's own `node_modules` subtree. The renderer is silently skipped, `entry-preview` never loads, and `renderToCanvas` is never registered.

## Fix

`import.meta.resolve('@storybook-astro/renderer')` produces an absolute `file://` URL resolved from the framework preset's own location, where the renderer is always accessible as a direct dependency. Storybook's `resolveAddonName` handles `file://` URLs correctly and loads the preset directly. This is the same pattern used by `@storybook/react-vite` and other official Storybook framework presets.

Closes #64

### CODE REVIEW

File: packages/@storybook-astro/framework/src/preset.ts [hunk 1]
```diff
@@ -12,7 +12,14 @@ import { mergeWithAstroConfig } from './vitePluginAstro.ts';
...
   builder: '@storybook/builder-vite',
-  renderer: '@storybook-astro/renderer'
+  // Use import.meta.resolve so Storybook receives an absolute file:// URL
+  // to the renderer preset rather than a bare package specifier.  When
+  // package managers like pnpm use strict node_modules isolation, bare
+  // specifiers are resolved from the *project root*, where the renderer
+  // (a dep of this framework, not the user's project) is not hoisted.
+  // The absolute URL is resolved from *this* file's location where the
+  // renderer is always accessible as a direct dependency.
+  renderer: import.meta.resolve('@storybook-astro/renderer')
```
Comment (slawekkolodziej) [inline packages/@storybook-astro/framework/src/preset.ts:22]: Looks good, the comment could be less verbose though 🙈

**Review by slawekkolodziej — APPROVED** [review]
